### ISSUE TITLE
后台无法批量导入用户信息

### ISSUE THREAD

**Issue by xiaopan233** [S2eTo/FlawPlatformMatch#1]
路径: /admin/users/user/import
当尝试上传xls文件以进行批量导入用户时，发现服务端返回500。
查看代码发现，在 users/admin.py 中，处理批量导入用户的函数 import_from_excel()，有一行判断
`if request.method == 'POST' and request.POST.get('post'):`
而请求时并未携带post参数，从而导致未进入正常代码逻辑报错。

**Comment by S2eTo** [comment]
已修复：https://github.com/S2eTo/FlawPlatformMatch/commit/fce019a810c10870df206015353561d4ee15837f
