### ISSUE TITLE
在搭建前端时出现问题

### ISSUE THREAD

**Issue by mcyydscc** [S2eTo/FlawPlatformMatch#3]
搭建前端时
npm run lint
使用此命令，会出现报错
![image](https://user-images.githubusercontent.com/90653809/181235401-5517da3c-ab70-4af0-8286-e9626a99bcfe.png)

**Comment by S2eTo** [comment]
项目没有安装 lint，你可以自行安装。

**Comment by mcyydscc** [comment]
> 项目没有安装 lint，你可以自行安装。

请问如果不执行这步对项目有很大的影响吗？

**Comment by S2eTo** [comment]
不影响程序运行

**Comment by mcyydscc** [comment]
> 不影响程序运行

大佬您好，在搭建后端时
创建迁移记录执行：pyhton3 manage.py makemigrations
出现如下错误
![image](https://user-images.githubusercontent.com/90653809/181249355-72410681-dc98-4d40-b880-912e296041e5.png)

之后我使用pip3 install django 安装了这个包，还是会出现这个错误
![image](https://user-images.githubusercontent.com/90653809/181249855-01f58d65-5a8d-4e94-8352-478b2a52783d.png)
