### ISSUE TITLE
登录页验证码无法显示

### ISSUE THREAD

**Issue by mcyydscc** [S2eTo/FlawPlatformMatch#4]
大佬您好，搭建之后在登录页验证码无法显示
![image](https://user-images.githubusercontent.com/90653809/182657585-95bb2f99-8105-44ef-9349-8b597daf26dc.png)
但是在后台日志中，验证码请求状态是200
![image](https://user-images.githubusercontent.com/90653809/182657929-e8709960-0e26-40fe-a7ca-0bb7e0698883.png)
访问/v1/get_captcha 也是正常的
![image](https://user-images.githubusercontent.com/90653809/182658006-97dcdad8-603e-4d1a-8a2d-5eb92261c89e.png)
搭建了两次都出现了这个问题

**Comment by S2eTo** [comment]
加一下QQ群：915098601

**Comment by mcyydscc** [comment]
> 915098601

![image](https://user-images.githubusercontent.com/90653809/184476328-5e840845-f0b9-4a67-b557-25c54566afa6.png)
大佬，有些页面必须要用到英文单引号，如果用中文单引号会导致页面进去就是flag，其他都不会执行，要怎么修改这个限制
