### ISSUE TITLE
搭建后效果和readme中的后台管理界面不一致

### ISSUE THREAD

**Issue by fwsilent** [S2eTo/FlawPlatformMatch#5]
大佬，搭建后，后台管理与介绍中的不一致，背景颜色不同，且没有队伍管理，用户管理的字段和介绍中的也不一致。目前群也搜不到了。

**Comment by mcyydscc** [comment]
战队在这个版本被删了，gitee有之前的版本，群被解散了

**Comment by S2eTo** [comment]
群号：512897146
